config/routes.rb
# Defines the app's routes
# @author Chris Loftus
Rails.application.routes.draw do
  resources :forums
  resources :users do
    # We add a special route to support the search field
    get 'search', on: :collection
  end

  # At the moment we only provide a JSON web service
  # API for user account managment. This is provided
  # as an example. See the rest_client folder.
  namespace :api, defaults: {format: :json} do
    resources :users, except: [:new, :edit] do
      get 'search', on: :collection
    end
  end

  namespace :api, defaults: {format: :json} do
    resources :forums, except: [:new, :destroy, :edit] do
      get 'search', on: :collection
    end
  end
  # No point allowing the editing or update of an existing broadcast
  resources :broadcasts, except: [:edit, :update]

  # A singleton resource and so no paths requiring ids are generated
  # Also, don't want to support editing of the session
  resource :session, only: [:new, :create, :destroy]

  # This is just to support the landing page
  get 'home', to: 'home#index', as: :home

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/forum.rb
class Forum < ApplicationRecord

validates :title, presence:true, length: {minimum: 3, maximum:20}
  validates :subject, presence:true, length: {minimum: 3, maximum:200}




# validates_presence_of :title, :author, :subject

has_many :replies, class_name: "Forum", foreign_key: "reply_id" , dependent: :destroy
belongs_to :reply, class_name: "Forum", optional: true



self.per_page = 16
end


app/controllers/api/forums_controller.rb
class API::ForumsController < API::ApplicationController



  # GET /forums.json


  def index
    @forums = Forum.all
    end
  end


  # GET /forums/new
  def new
    @forum = Forum.new

  end
  # GET /forums/1/edit
  def edit
    @forum = Forum.find(params[:id])
  end
  # PATCH/PUT /forums/1
  # PATCH/PUT /forums/1.json

  def update
    @forum = Forum.find(params[:id])
    respond_to do |format|
      if @forum.update(forum_params)

        format.json { render :show, status: :ok, location: @forum }
      else

        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end
  # POST /forums
  # POST /forums.json
  def create
    @forum = Forum.new(forum_params)
    respond_to do |f|

      if @forum.save


        f.json { render :show, status: :created, location: @forum }
      else

        f.json { render json: @forum.errors, status: :unprocessable_entity }

      end
    end

  end

  # GET /forums/1
  # GET /forums/1.json
  def show

    @forum = Forum.find(params[:id])
  end
  # DELETE /forums/1
  # DELETE /forums/1.json
  def destroy
    @forum = Forum.find(params[:id])
    @forum.destroy
    flash[:notice] = "Forum was successfuly deleted"
    redirect_to forums_path
  end
  def forum_params
    params.require(:forum).permit(:title, :author, :subject, :user_id, :comment, :comment_id)


  end



app/controllers/forums_controller.rb
class ForumsController <ApplicationController

   # GET /forums
  # GET /forums.json

  rescue_from ActiveRecord::RecordNotFound, with: :show_record_not_found

  def index

  @forums = Forum.all.paginate(:page => params[:page], :per_page => 10)
  end
  def show
    @forum = Forum.find(params[:id])
  end

  # GET /forums/new
def new
@forum = Forum.new
end
  # GET /forums/1/edit
def edit
@forum = Forum.find(params[:id])
end
  # PATCH/PUT /forums/1
  # PATCH/PUT /forums/1.json

def update
  @forum = Forum.find(params[:id])
  respond_to do |format|
    if @forum.update(forum_params)
      format.html { redirect_to forum_path(@forum), notice: 'Post was successfully updated.'}
      format.json { render :show, status: :ok, location: @forum }
    else
      format.html { render :edit }
      format.json { render json: @forum.errors, status: :unprocessable_entity }
    end
  end
end
  # POST /forums
  # POST /forums.json
  def create
    @forum = Forum.new(forum_params)
    respond_to do |f|

    if @forum.save

      f.html { redirect_to @forum, notice: 'Thread added successfully.' }
      f.json { render :show, status: :created, location: @forum }
    else
      f.html { render :new }
        f.json { render json: @forum.errors, status: :unprocessable_entity }

    end
      end

  end


  # DELETE /forums/1
  # DELETE /forums/1.json
def destroy
  @forum = Forum.find(params[:id])
  @forum.destroy
  flash[:notice] = "Forum was successfuly deleted"
  redirect_to forums_path



end
def forum_params
  params.require(:forum).permit( :title, :author, :subject, :user_id, :comment, :comment_id)


end
end



app/views/forums/_comment.html.erb
<%= form_with(model: forum, local: true) do |form| %>
    <% if forum.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

          <ul>
            <% post.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= form.label :comment %>
      <%= form.text_area :comment, id: :post_comment %>
    </div>

    <div class="actions">
      <%= form.submit 'Add Comment' %>
    </div>
<%end%>
<Strong> Comments</Strong>
<%= @forum.comment%>


app/views/forums/_form.html.erb
<%= form_for( @forum, local: true) do |f| %>
    <% if @forum.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@forum.errors.count, "error") %> prohibited this post from being saved:</h2>
        </div>
          <ul>
            <% @forum.errors.full_messages.each do |m| %>
                <li><%= m %></li>
            <% end %>

    <% end %>
<p>
      <%= f.label :title %>
      <%= f.text_field :title, id: :forum_title %>
</p>
    <br>
    <p>
      <%= f.label :'Would you like to post this Anonymously?' %>
      <%= f.check_box :author, {}, 'anonymous', current_user.login %>
<br>
    </p>
    <br>
      <%= f.label :subject %>
      <%= f.text_area :subject, id: :forum_subject %>
    </p>
    <br>
    <div class="actions">
      <%= f.submit %>


</div>
    </ul>


<% end %>

<br>
<%= link_to "Back To forum", forums_path %>

app/views/forums/edit.html.erb
<h1> Edit Existing Forum</h1>

<%= render 'form' %>

app/views/forums/index.html.erb
<h1> All forums</h1>

<table>
<tr>

  <th>Title</th>
  <th>Author</th>
  <th>Unread posts</th>
  <th>Total number of posts</th>
<tbody>
  <% @forums.each do |forum| %>




          <tr colspan = "4">
            <td><%= link_to forum.title, forum %></td>
            <td><%= forum.author %></td>
            <td><%= Forum.count('comment') %></td>
            <td> <%= Forum.count('author') %> </td>




            <% end %>



</tbody>
</table>
</tr>

</table>

<br>
<div class="digg_pagination">
  <div>
    <%= page_entries_info @forums %>
  </div>
  <%= will_paginate @forums, container: false %>
</div>
<br>
<%= link_to 'Create New Forum', new_forum_path %>

app/views/forums/new.html.erb
<h1> Create a new Forum</h1>

<%= render 'form' %>

app/views/forums/show.html.erb
<h1> Showing selected Forum</h1>
<br>

<p>
<strong> Title:</strong> <%= @forum.title %>
</p>

<p>
<strong> Author:</strong> <%= @forum.author%>
</p>

<p>
  <strong> Subject</strong> <%= @forum.subject%>
</p>

<% if is_admin? || @forum.author == current_user.login %>
    <td><%= link_to 'Edit', edit_forum_path(@forum) %></td>
    <td><%= link_to 'Destroy', @forum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
<% end %>



<%= link_to 'Back', forums_path %>

<%if @forum.replies %>
    <%=render 'comment', forum: @forum %>
<% end %>
<br>
